before_install:
    openssl aes-256-cbc -K $encrypted_4c5164587105_key -iv $encrypted_4c5164587105_iv -in test.txt.enc -out test.txt -d
branches:
    only:
        - raf
        - master
        - marin_dev
        - develop
        - marin_reform
language: php
php:
    - 5.5
    - 5.4
    - 5.3
script:
    - phpunit tests/IcebergTest.php
