branches:
    only:
        - raf
        - master
        - marin_dev
        - develop
        - marin_reform
language: php
php:
    - 5.5
    - 5.4
    - 5.3
script:
    - phpunit tests/IcebergTest.php
env :
    secure: "n2F6gRtKENTaZPPg9SmQP5YnqAp3wKqN3QLNQhBAhMdYNz5NuO1jZLJRSXFKSo6mu3R16ugk6hODyaIP6s2lJoejSqk2/KL/OtBdI6fEUWq5tubnovYp7kXWvD0rwZnZ3m1S66wNaB4eIz1XTX28GXGEGfHNGYiiIcG1Hf9BwH8="
